# Generated by Django 5.2.17 on 2026-09-24 01:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bridge", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="ingestkey",
            name="environment",
            field=models.CharField(
                choices=[("lab", "Lab"), ("test", "Test")], default="lab", max_length=12
            ),
        ),
    ]
