# Generated by Django 5.2.17 on 2026-09-24 02:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bridge", "0002_ingestkey_environment"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="source",
            field=models.CharField(
                choices=[
                    ("migration_lab", "Observed SQL lab"),
                    ("synthetic_demo", "Synthetic fixture"),
                    ("legacy_unclassified", "Earlier development record"),
                ],
                default="legacy_unclassified",
                max_length=24,
            ),
        ),
        migrations.AddField(
            model_name="ingestkey",
            name="source",
            field=models.CharField(
                choices=[("migration_lab", "Migration lab"), ("synthetic_demo", "Synthetic demo")],
                default="migration_lab",
                max_length=24,
            ),
        ),
    ]
