# Generated by Django 5.2.17 on 2026-09-24 03:14

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bridge", "0003_event_source_ingestkey_source"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Finding",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("tool", models.CharField(max_length=100)),
                ("fingerprint", models.CharField(max_length=64)),
                ("severity", models.CharField(max_length=16)),
                ("rule_id", models.CharField(max_length=160)),
                ("title", models.CharField(max_length=240)),
                ("path", models.CharField(blank=True, max_length=500)),
                ("line", models.PositiveIntegerField(blank=True, null=True)),
                ("package", models.CharField(blank=True, max_length=160)),
                ("package_version", models.CharField(blank=True, max_length=100)),
                ("fix_versions", models.JSONField(default=list)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("reviewed", "Reviewed"),
                            ("accepted_risk", "Accepted risk"),
                            ("false_positive", "False positive"),
                        ],
                        default="open",
                        max_length=20,
                    ),
                ),
                ("version", models.PositiveIntegerField(default=1)),
                ("first_seen", models.DateTimeField(auto_now_add=True)),
                ("last_seen", models.DateTimeField(auto_now_add=True)),
                (
                    "integration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="bridge.integration"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ScanRun",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("format", models.CharField(max_length=16)),
                ("tool", models.CharField(max_length=100)),
                ("tool_version", models.CharField(blank=True, max_length=80)),
                ("digest", models.CharField(max_length=64)),
                ("identity_digest", models.CharField(max_length=64, unique=True)),
                (
                    "provenance",
                    models.CharField(
                        choices=[
                            ("claimed_report", "Imported report"),
                            ("local_execution", "Local execution"),
                        ],
                        max_length=24,
                    ),
                ),
                ("source_revision", models.CharField(blank=True, max_length=64)),
                ("manifest", models.JSONField(default=dict)),
                ("execution", models.JSONField(default=dict)),
                ("coverage_status", models.CharField(max_length=16)),
                ("input_count", models.PositiveIntegerField(default=0)),
                ("skipped_count", models.PositiveIntegerField(default=0)),
                ("suppressed_count", models.PositiveIntegerField(default=0)),
                ("finding_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "imported_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "integration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="bridge.integration"
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="FindingObservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("severity", models.CharField(max_length=16)),
                ("rule_id", models.CharField(max_length=160)),
                ("title", models.CharField(max_length=240)),
                ("path", models.CharField(blank=True, max_length=500)),
                ("line", models.PositiveIntegerField(blank=True, null=True)),
                ("package", models.CharField(blank=True, max_length=160)),
                ("package_version", models.CharField(blank=True, max_length=100)),
                ("fix_versions", models.JSONField(default=list)),
                ("suppressed", models.BooleanField(default=False)),
                ("suppression_statuses", models.JSONField(default=list)),
                (
                    "finding",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="observations",
                        to="bridge.finding",
                    ),
                ),
                (
                    "scan_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="observations",
                        to="bridge.scanrun",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="finding",
            index=models.Index(
                fields=["integration", "status", "last_seen"], name="bridge_find_integra_6d81d1_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="finding",
            constraint=models.UniqueConstraint(
                fields=("integration", "tool", "fingerprint"), name="unique_app_tool_finding"
            ),
        ),
        migrations.AddConstraint(
            model_name="finding",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("status__in", ["open", "reviewed", "accepted_risk", "false_positive"])
                ),
                name="valid_finding_status",
            ),
        ),
        migrations.AddIndex(
            model_name="scanrun",
            index=models.Index(
                fields=["integration", "tool", "created_at"], name="bridge_scan_integra_a2e761_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="findingobservation",
            constraint=models.UniqueConstraint(
                fields=("scan_run", "finding"), name="unique_scan_finding"
            ),
        ),
    ]
