# Generated by Django 5.2.17 on 2026-09-24 05:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bridge", "0004_scanner_findings"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="event",
            index=models.Index(fields=["integration", "received_at"], name="sb_event_app_received"),
        ),
    ]
