# Generated by Django 5.2.17 on 2026-09-25 01:01

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bridge", "0005_event_received_index"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PracticeSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("scenario", models.CharField(max_length=40)),
                ("snapshot", models.JSONField()),
                ("snapshot_hash", models.CharField(max_length=64)),
                ("status", models.CharField(default="draft", max_length=12)),
                ("version", models.PositiveIntegerField(default=1)),
                ("revealed", models.JSONField(default=list)),
                ("decision", models.JSONField(default=dict)),
                ("review", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("submitted_at", models.DateTimeField(null=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "integration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="bridge.integration"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PracticeEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("version", models.PositiveIntegerField()),
                ("action", models.CharField(max_length=12)),
                ("content", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="entries",
                        to="bridge.practicesession",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="practicesession",
            index=models.Index(
                fields=["author", "integration", "-created_at"], name="sb_practice_owner"
            ),
        ),
        migrations.AddConstraint(
            model_name="practicesession",
            constraint=models.CheckConstraint(
                condition=models.Q(("status__in", ["draft", "submitted"])),
                name="valid_practice_status",
            ),
        ),
        migrations.AddConstraint(
            model_name="practiceentry",
            constraint=models.UniqueConstraint(
                fields=("session", "version"), name="unique_practice_version"
            ),
        ),
    ]
