# Generated by Django 5.2.17 on 2026-09-25 01:24

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bridge", "0006_analyst_practice"),
    ]

    operations = [
        migrations.CreateModel(
            name="SocBatch",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("body", models.TextField()),
                ("body_sha256", models.CharField(max_length=64)),
                ("start_offset", models.PositiveIntegerField()),
                ("record_count", models.PositiveIntegerField()),
                ("state", models.CharField(default="staged", max_length=16)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("appended_at", models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="SocDelivery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="bridge.socbatch"
                    ),
                ),
                (
                    "event",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT, to="bridge.event"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SocStream",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("offset", models.PositiveIntegerField(default=0)),
                (
                    "prefix_sha256",
                    models.CharField(
                        default="e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
                        max_length=64,
                    ),
                ),
                ("revision", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "integration",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT, to="bridge.integration"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="socbatch",
            name="stream",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="bridge.socstream"
            ),
        ),
        migrations.AddConstraint(
            model_name="socbatch",
            constraint=models.UniqueConstraint(
                condition=models.Q(("state", "staged")),
                fields=("stream",),
                name="one_staged_soc_batch",
            ),
        ),
        migrations.AddConstraint(
            model_name="socbatch",
            constraint=models.CheckConstraint(
                condition=models.Q(("state__in", ["staged", "file_appended"])),
                name="valid_soc_batch_state",
            ),
        ),
    ]
