# Generated by Django 5.2.17 on 2026-10-01 21:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bridge", "0009_enterprise_processing"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="source",
            field=models.CharField(
                choices=[
                    ("migration_lab", "Observed SQL lab"),
                    ("synthetic_demo", "Synthetic fixture"),
                    ("instrumented_lab", "Instrumented source lab"),
                    ("legacy_unclassified", "Earlier development record"),
                ],
                default="legacy_unclassified",
                max_length=24,
            ),
        ),
        migrations.AlterField(
            model_name="ingestkey",
            name="source",
            field=models.CharField(
                choices=[
                    ("migration_lab", "Migration lab"),
                    ("synthetic_demo", "Synthetic demo"),
                    ("instrumented_lab", "Instrumented source lab"),
                ],
                default="migration_lab",
                max_length=24,
            ),
        ),
    ]
