# Generated by Django 5.2.17 on 2026-10-01 22:35

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bridge", "0010_alter_event_source_alter_ingestkey_source"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="integration",
            name="asset_criticality",
            field=models.CharField(
                choices=[
                    ("unassessed", "Not assessed"),
                    ("low", "Low"),
                    ("moderate", "Moderate"),
                    ("high", "High"),
                    ("critical", "Critical"),
                ],
                default="unassessed",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="integration",
            name="business_owner",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="investigation",
            name="acknowledged_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="investigation",
            name="acknowledged_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="acknowledged_cases",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="investigation",
            name="assignee",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="bridge.membership",
            ),
        ),
        migrations.AddField(
            model_name="investigation",
            name="due_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="note",
            name="kind",
            field=models.CharField(
                choices=[
                    ("general", "General / earlier note"),
                    ("observed_fact", "Observed fact"),
                    ("interpretation", "Analyst interpretation"),
                    ("uncertainty", "Uncertainty"),
                    ("remediation", "Remediation plan"),
                    ("verification", "Verification note"),
                ],
                default="general",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="CaseTask",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[("review", "Review"), ("remediation", "Remediation")],
                        max_length=12,
                    ),
                ),
                ("title", models.CharField(max_length=160)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("in_progress", "In progress"),
                            ("awaiting_retest", "Awaiting retest"),
                        ],
                        default="open",
                        max_length=16,
                    ),
                ),
                ("case_version", models.PositiveIntegerField()),
                ("evidence_sha256", models.CharField(max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assignee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="bridge.membership",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "investigation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tasks",
                        to="bridge.investigation",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ServiceCredential",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("key_id", models.CharField(max_length=64, unique=True)),
                ("secret_env", models.CharField(max_length=100, unique=True)),
                ("active", models.BooleanField(default=True)),
                (
                    "capability",
                    models.CharField(
                        choices=[
                            ("read_case_evidence", "Read case evidence"),
                            ("create_review_task", "Create review task"),
                        ],
                        max_length=24,
                    ),
                ),
                (
                    "integration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="bridge.integration"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ServiceNonce",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("nonce", models.UUIDField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "credential",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="bridge.servicecredential"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ServiceRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("idempotency_key", models.UUIDField()),
                ("request_sha256", models.CharField(max_length=64)),
                ("response", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "credential",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="bridge.servicecredential"
                    ),
                ),
                (
                    "task",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT, to="bridge.casetask"
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="casetask",
            constraint=models.CheckConstraint(
                condition=models.Q(("kind__in", ["review", "remediation"])),
                name="valid_case_task_kind",
            ),
        ),
        migrations.AddConstraint(
            model_name="casetask",
            constraint=models.CheckConstraint(
                condition=models.Q(("status__in", ["open", "in_progress", "awaiting_retest"])),
                name="valid_case_task_state",
            ),
        ),
        migrations.AddConstraint(
            model_name="servicecredential",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("capability__in", ["read_case_evidence", "create_review_task"])
                ),
                name="valid_service_capability",
            ),
        ),
        migrations.AddIndex(
            model_name="servicenonce",
            index=models.Index(fields=["credential", "created_at"], name="sb_service_nonce_time"),
        ),
        migrations.AddConstraint(
            model_name="servicenonce",
            constraint=models.UniqueConstraint(
                fields=("credential", "nonce"), name="unique_service_nonce"
            ),
        ),
        migrations.AddConstraint(
            model_name="servicerequest",
            constraint=models.UniqueConstraint(
                fields=("credential", "idempotency_key"), name="unique_service_request"
            ),
        ),
    ]
