# Generated by Django 5.2.17 on 2026-10-02 00:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bridge", "0011_integration_asset_criticality_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="event",
            index=models.Index(
                fields=["integration", "environment", "source", "actor", "occurred_at"],
                name="sb_event_actor_scope_time",
            ),
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(
                fields=["integration", "environment", "source", "resource", "occurred_at"],
                name="sb_event_resource_scope_time",
            ),
        ),
    ]
