# Generated by Django 5.2.17 on 2026-10-02 08:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bridge", "0012_extended_correlation_indexes"),
    ]

    operations = [
        migrations.CreateModel(
            name="MetricsScrapeState",
            fields=[
                (
                    "id",
                    models.PositiveSmallIntegerField(
                        default=1, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("last_started_at", models.DateTimeField()),
            ],
            options={
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("id", 1)), name="sb_metrics_singleton"
                    )
                ],
            },
        ),
    ]
