# Generated by Django 5.2.17 on 2026-10-02 08:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bridge", "0013_metricsscrapestate"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="event",
            index=models.Index(
                fields=["integration", "state", "processed_at"], name="sb_event_app_completion"
            ),
        ),
    ]
