# Generated by Django 5.2.17 on 2026-10-02 09:56

import datetime
import uuid

import django.db.models.deletion
import django.db.models.expressions
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bridge", "0014_event_sb_event_app_completion"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FederatedIdentity",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("issuer", models.CharField(max_length=255)),
                ("subject", models.CharField(max_length=255)),
                ("enabled", models.BooleanField(default=True)),
                ("version", models.PositiveIntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FederatedSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("identity_version", models.PositiveIntegerField()),
                ("binding_digest", models.CharField(max_length=64, unique=True)),
                (
                    "provider_session_digest",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("created_at", models.DateTimeField()),
                ("authenticated_at", models.DateTimeField()),
                ("expires_at", models.DateTimeField(db_index=True)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                (
                    "identity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="bridge.federatedidentity"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="IdentityAudit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("session_id", models.UUIDField(null=True)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("link.provisioned", "Link provisioned"),
                            ("link.disabled", "Link disabled"),
                            ("link.enabled", "Link enabled"),
                            ("session.issued", "Session issued"),
                            ("session.revoked", "Session revoked"),
                        ],
                        max_length=24,
                    ),
                ),
                (
                    "origin",
                    models.CharField(
                        choices=[
                            ("local_operator", "Trusted local database operator"),
                            ("validated_oidc", "Validated OIDC admission"),
                            ("local_session", "Local browser session"),
                        ],
                        max_length=24,
                    ),
                ),
                ("identity_version", models.PositiveIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "identity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="bridge.federatedidentity"
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="federatedidentity",
            constraint=models.UniqueConstraint(
                fields=("issuer", "subject"), name="sb_identity_issuer_subject"
            ),
        ),
        migrations.AddConstraint(
            model_name="federatedidentity",
            constraint=models.CheckConstraint(
                condition=models.Q(("version__gte", 1)), name="sb_identity_version_positive"
            ),
        ),
        migrations.AddConstraint(
            model_name="federatedsession",
            constraint=models.CheckConstraint(
                condition=models.Q(("expires_at__gt", models.F("created_at"))),
                name="sb_sso_positive_lifetime",
            ),
        ),
        migrations.AddConstraint(
            model_name="federatedsession",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "expires_at__lte",
                        django.db.models.expressions.CombinedExpression(
                            models.F("created_at"),
                            "+",
                            models.Value(datetime.timedelta(seconds=900)),
                        ),
                    )
                ),
                name="sb_sso_max_lifetime",
            ),
        ),
        migrations.AddConstraint(
            model_name="federatedsession",
            constraint=models.CheckConstraint(
                condition=models.Q(("identity_version__gte", 1)), name="sb_sso_link_version"
            ),
        ),
        migrations.AddConstraint(
            model_name="identityaudit",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "action__in",
                        [
                            "link.provisioned",
                            "link.disabled",
                            "link.enabled",
                            "session.issued",
                            "session.revoked",
                        ],
                    )
                ),
                name="sb_identity_audit_action",
            ),
        ),
        migrations.AddConstraint(
            model_name="identityaudit",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("origin__in", ["local_operator", "validated_oidc", "local_session"])
                ),
                name="sb_identity_audit_origin",
            ),
        ),
    ]
