# Generated by Django 5.2.17 on 2026-10-02 11:08

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bridge", "0015_federatedidentity_federatedsession_identityaudit_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CaseVerification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("case_version", models.PositiveIntegerField()),
                ("evidence_sha256", models.CharField(max_length=64)),
                ("check_digest", models.CharField(max_length=64)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Awaiting review"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=12,
                    ),
                ),
                ("rationale", models.CharField(blank=True, max_length=1000)),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                ("decided_at", models.DateTimeField(null=True)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name="casetask",
            name="valid_case_task_state",
        ),
        migrations.AlterField(
            model_name="casetask",
            name="status",
            field=models.CharField(
                choices=[
                    ("open", "Open"),
                    ("in_progress", "In progress"),
                    ("awaiting_retest", "Awaiting retest"),
                    ("verified", "Verified in recorded lab"),
                ],
                default="open",
                max_length=16,
            ),
        ),
        migrations.AddConstraint(
            model_name="casetask",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("status__in", ["open", "in_progress", "awaiting_retest", "verified"])
                ),
                name="valid_case_task_state",
            ),
        ),
        migrations.AddField(
            model_name="caseverification",
            name="check_run",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="bridge.checkrun"
            ),
        ),
        migrations.AddField(
            model_name="caseverification",
            name="reviewer",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="reviewed_verifications",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="caseverification",
            name="submitted_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="submitted_verifications",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="caseverification",
            name="task",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="verifications",
                to="bridge.casetask",
            ),
        ),
        migrations.AddConstraint(
            model_name="caseverification",
            constraint=models.UniqueConstraint(
                fields=("task", "check_run", "case_version"), name="unique_case_retest_submission"
            ),
        ),
        migrations.AddConstraint(
            model_name="caseverification",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("decided_at__isnull", True),
                        ("rationale", ""),
                        ("reviewer__isnull", True),
                        ("status", "pending"),
                    ),
                    models.Q(
                        ("decided_at__isnull", False),
                        ("reviewer__isnull", False),
                        ("status__in", ["approved", "rejected"]),
                        models.Q(("rationale", ""), _negated=True),
                    ),
                    _connector="OR",
                ),
                name="valid_case_verification_decision",
            ),
        ),
        migrations.AddConstraint(
            model_name="caseverification",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("reviewer__isnull", True),
                    models.Q(("reviewer", models.F("submitted_by")), _negated=True),
                    _connector="OR",
                ),
                name="independent_case_verification_reviewer",
            ),
        ),
    ]
