# Generated by Django 5.2.17 on 2026-10-02 11:44

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bridge", "0016_caseverification_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ForwardedDetection",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("case_version", models.PositiveIntegerField()),
                ("rule_version", models.CharField(max_length=40)),
                ("evidence_sha256", models.CharField(max_length=64)),
                ("generation_source_sha256", models.CharField(max_length=64)),
                ("packet", models.JSONField()),
                ("packet_sha256", models.CharField(max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="WazuhCursor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("collector_run", models.UUIDField()),
                (
                    "kind",
                    models.CharField(
                        choices=[("archive", "Archive"), ("alert", "Alert")], max_length=8
                    ),
                ),
                ("segment", models.PositiveSmallIntegerField(default=0)),
                ("offset", models.PositiveIntegerField(default=0)),
                (
                    "prefix_sha256",
                    models.CharField(
                        default="e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
                        max_length=64,
                    ),
                ),
                ("physical_records", models.PositiveIntegerField(default=0)),
                ("last_native_at", models.DateTimeField(null=True)),
                ("last_import_at", models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="WazuhRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("collector_run", models.UUIDField()),
                ("native_id", models.CharField(max_length=80)),
                (
                    "kind",
                    models.CharField(
                        choices=[("archive", "Archive"), ("alert", "Alert")], max_length=8
                    ),
                ),
                ("rule_id", models.CharField(blank=True, max_length=6)),
                ("rule_level", models.PositiveSmallIntegerField(null=True)),
                ("occurred_at", models.DateTimeField()),
                ("packet_sha256", models.CharField(max_length=64)),
                ("record_sha256", models.CharField(max_length=64)),
                ("imported_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name="socstream",
            name="channel",
            field=models.CharField(
                choices=[
                    ("observation", "Source observations"),
                    ("detection", "Forwarded detections"),
                ],
                default="observation",
                max_length=12,
            ),
        ),
        migrations.AddField(
            model_name="socstream",
            name="selection_after",
            field=models.UUIDField(null=True),
        ),
        migrations.AlterField(
            model_name="socstream",
            name="integration",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="bridge.integration"
            ),
        ),
        migrations.AddConstraint(
            model_name="socstream",
            constraint=models.UniqueConstraint(
                fields=("integration", "channel"), name="unique_soc_channel"
            ),
        ),
        migrations.AddConstraint(
            model_name="socstream",
            constraint=models.CheckConstraint(
                condition=models.Q(("channel__in", ["observation", "detection"])),
                name="valid_soc_channel",
            ),
        ),
        migrations.AddField(
            model_name="forwardeddetection",
            name="batch",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="bridge.socbatch"
            ),
        ),
        migrations.AddField(
            model_name="forwardeddetection",
            name="investigation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="bridge.investigation"
            ),
        ),
        migrations.AddField(
            model_name="wazuhcursor",
            name="integration",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="bridge.integration"
            ),
        ),
        migrations.AddField(
            model_name="wazuhrecord",
            name="event",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.PROTECT, to="bridge.event"
            ),
        ),
        migrations.AddField(
            model_name="wazuhrecord",
            name="integration",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="bridge.integration"
            ),
        ),
        migrations.AddField(
            model_name="wazuhrecord",
            name="signal",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="bridge.forwardeddetection",
            ),
        ),
        migrations.AddConstraint(
            model_name="forwardeddetection",
            constraint=models.UniqueConstraint(
                fields=(
                    "investigation",
                    "evidence_sha256",
                    "generation_source_sha256",
                    "rule_version",
                ),
                name="unique_forwarded_detection_snapshot",
            ),
        ),
        migrations.AddConstraint(
            model_name="wazuhcursor",
            constraint=models.UniqueConstraint(
                fields=("integration", "collector_run", "kind"), name="unique_wazuh_cursor"
            ),
        ),
        migrations.AddConstraint(
            model_name="wazuhcursor",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("kind__in", ["archive", "alert"]),
                    ("offset__lte", 4194304),
                    ("segment__lte", 7),
                ),
                name="bounded_wazuh_cursor",
            ),
        ),
        migrations.AddConstraint(
            model_name="wazuhrecord",
            constraint=models.UniqueConstraint(
                fields=("integration", "collector_run", "kind", "native_id"),
                name="unique_wazuh_native_record",
            ),
        ),
        migrations.AddConstraint(
            model_name="wazuhrecord",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("event__isnull", False), ("signal__isnull", True)),
                    models.Q(("event__isnull", True), ("signal__isnull", False)),
                    _connector="OR",
                ),
                name="one_wazuh_record_target",
            ),
        ),
        migrations.AddConstraint(
            model_name="wazuhrecord",
            constraint=models.CheckConstraint(
                condition=models.Q(("kind__in", ["archive", "alert"])),
                name="valid_wazuh_record_kind",
            ),
        ),
    ]
