# Generated by Django 5.2.17 on 2026-10-02 18:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bridge", "0017_forwardeddetection_wazuhcursor_wazuhrecord_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="socstream",
            name="segmented_export",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="SocSegment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("number", models.PositiveSmallIntegerField()),
                ("start_offset", models.PositiveIntegerField()),
                ("byte_count", models.PositiveIntegerField(default=0)),
                (
                    "prefix_sha256",
                    models.CharField(
                        default="e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
                        max_length=64,
                    ),
                ),
                ("sealed_at", models.DateTimeField(null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "stream",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="segments",
                        to="bridge.socstream",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="socbatch",
            name="segment",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.PROTECT, to="bridge.socsegment"
            ),
        ),
        migrations.AddConstraint(
            model_name="socsegment",
            constraint=models.UniqueConstraint(
                fields=("stream", "number"), name="unique_soc_segment"
            ),
        ),
        migrations.AddConstraint(
            model_name="socsegment",
            constraint=models.UniqueConstraint(
                condition=models.Q(("sealed_at__isnull", True)),
                fields=("stream",),
                name="one_open_soc_segment",
            ),
        ),
        migrations.AddConstraint(
            model_name="socsegment",
            constraint=models.CheckConstraint(
                condition=models.Q(("byte_count__lte", 2097152), ("number__lte", 7)),
                name="bounded_soc_segment",
            ),
        ),
    ]
