# Generated by Django 5.2.17 on 2026-10-02 22:01

import datetime

import django.db.models.expressions
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bridge", "0018_soc_segmented_export"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FederatedExchange",
            fields=[
                (
                    "state_digest",
                    models.CharField(max_length=64, primary_key=True, serialize=False),
                ),
                ("browser_digest", models.CharField(max_length=64)),
                ("issuer_digest", models.CharField(max_length=64)),
                ("created_at", models.DateTimeField()),
                ("expires_at", models.DateTimeField(db_index=True)),
                ("consumed_at", models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="FederatedFlowWindow",
            fields=[
                ("operation", models.CharField(max_length=12, primary_key=True, serialize=False)),
                ("window_start", models.DateTimeField()),
                ("requests", models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="FederatedLogoutNotice",
            fields=[
                (
                    "token_digest",
                    models.CharField(max_length=64, primary_key=True, serialize=False),
                ),
                ("scope_digest", models.CharField(max_length=64)),
                ("received_at", models.DateTimeField()),
                ("block_until", models.DateTimeField(db_index=True)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name="identityaudit",
            name="sb_identity_audit_origin",
        ),
        migrations.AlterField(
            model_name="identityaudit",
            name="origin",
            field=models.CharField(
                choices=[
                    ("local_operator", "Trusted local database operator"),
                    ("validated_oidc", "Validated OIDC admission"),
                    ("local_session", "Local browser session"),
                    ("provider_logout", "Validated provider logout"),
                ],
                max_length=24,
            ),
        ),
        migrations.AddConstraint(
            model_name="identityaudit",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "origin__in",
                        ["local_operator", "validated_oidc", "local_session", "provider_logout"],
                    )
                ),
                name="sb_identity_audit_origin",
            ),
        ),
        migrations.AddConstraint(
            model_name="federatedexchange",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("expires_at__gt", models.F("created_at")),
                    (
                        "expires_at__lte",
                        django.db.models.expressions.CombinedExpression(
                            models.F("created_at"),
                            "+",
                            models.Value(datetime.timedelta(seconds=300)),
                        ),
                    ),
                ),
                name="sb_exchange_lifetime",
            ),
        ),
        migrations.AddConstraint(
            model_name="federatedflowwindow",
            constraint=models.CheckConstraint(
                condition=models.Q(("operation__in", ["login", "logout"])),
                name="sb_federated_window_scope",
            ),
        ),
        migrations.AddIndex(
            model_name="federatedlogoutnotice",
            index=models.Index(
                fields=["scope_digest", "block_until"], name="sb_logout_scope_expiry"
            ),
        ),
        migrations.AddConstraint(
            model_name="federatedlogoutnotice",
            constraint=models.CheckConstraint(
                condition=models.Q(("block_until__gt", models.F("received_at"))),
                name="sb_logout_block_lifetime",
            ),
        ),
    ]
