# Generated by Django 5.2.17 on 2026-10-02 22:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bridge", "0019_federatedexchange_federatedflowwindow_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="identityaudit",
            name="sb_identity_audit_action",
        ),
        migrations.AlterField(
            model_name="identityaudit",
            name="action",
            field=models.CharField(
                choices=[
                    ("link.provisioned", "Link provisioned"),
                    ("link.disabled", "Link disabled"),
                    ("link.enabled", "Link enabled"),
                    ("session.issued", "Session issued"),
                    ("session.revoked", "Session revoked"),
                    ("account.recovered", "Local account recovery"),
                ],
                max_length=24,
            ),
        ),
        migrations.AddConstraint(
            model_name="identityaudit",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "action__in",
                        [
                            "link.provisioned",
                            "link.disabled",
                            "link.enabled",
                            "session.issued",
                            "session.revoked",
                            "account.recovered",
                        ],
                    )
                ),
                name="sb_identity_audit_action",
            ),
        ),
    ]
