# Generated by Django 5.2.17 on 2026-10-02 22:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bridge", "0020_remove_identityaudit_sb_identity_audit_action_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="federatedflowwindow",
            name="sb_federated_window_scope",
        ),
        migrations.AddConstraint(
            model_name="federatedflowwindow",
            constraint=models.CheckConstraint(
                condition=models.Q(("operation__in", ["login", "logout", "protocol"])),
                name="sb_federated_window_scope",
            ),
        ),
    ]
