# Generated by Django 5.2.17 on 2026-10-05 04:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bridge", "0021_remove_federatedflowwindow_sb_federated_window_scope_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="LeaverSignal",
            fields=[
                ("jti", models.CharField(max_length=32, primary_key=True, serialize=False)),
                ("txn", models.CharField(blank=True, default="", max_length=128)),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("account_disabled", "Account disabled"),
                            ("session_revoked", "Sessions revoked"),
                            ("session_established", "Sign-in after departure"),
                        ],
                        max_length=24,
                    ),
                ),
                ("subject_issuer", models.CharField(max_length=255)),
                ("subject_id", models.CharField(max_length=255)),
                ("event_at", models.DateTimeField()),
                ("issued_at", models.DateTimeField()),
                ("initiating_entity", models.CharField(blank=True, default="", max_length=16)),
                ("reason", models.CharField(blank=True, default="", max_length=200)),
                ("key_id", models.CharField(max_length=64)),
                ("token", models.TextField()),
                ("token_sha256", models.CharField(max_length=64)),
                ("facts_sha256", models.CharField(max_length=64)),
                ("received_at", models.DateTimeField()),
                (
                    "cases",
                    models.ManyToManyField(
                        blank=True, related_name="leaver_signals", to="bridge.investigation"
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["subject_issuer", "subject_id", "event_type"],
                        name="sb_leaver_subject",
                    )
                ],
            },
        ),
    ]
