# Generated by Django 5.2.17 on 2026-10-01 21:34

import datetime
import uuid

import django.db.models.deletion
import django.db.models.expressions
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LoginAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("occurred_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Outbox",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "app",
                    models.CharField(
                        choices=[
                            ("documents", "Private documents"),
                            ("expenses", "Expense records"),
                        ],
                        max_length=12,
                    ),
                ),
                ("payload", models.JSONField()),
                ("digest", models.CharField(max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("state", models.CharField(default="pending", max_length=12)),
                ("attempts", models.PositiveIntegerField(default=0)),
                ("available_at", models.DateTimeField()),
                ("acknowledged_at", models.DateTimeField(null=True)),
                ("error_code", models.CharField(blank=True, max_length=32)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["state", "available_at", "created_at"], name="ref_outbox_queue"
                    )
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("app__in", ["documents", "expenses"])),
                        name="ref_outbox_app",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("state__in", ["pending", "acknowledged", "dead"])),
                        name="ref_outbox_state",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Resource",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "app",
                    models.CharField(
                        choices=[
                            ("documents", "Private documents"),
                            ("expenses", "Expense records"),
                        ],
                        max_length=12,
                    ),
                ),
                ("label", models.CharField(max_length=80)),
                ("synthetic_content", models.CharField(max_length=512)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Grant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[("group", "Group"), ("direct", "Direct")], max_length=8
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "resource",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="reference_lab.resource"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BoundedFault",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("enabled", models.BooleanField(default=False)),
                ("started_at", models.DateTimeField()),
                ("expires_at", models.DateTimeField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "resource",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="reference_lab.resource"
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="resource",
            constraint=models.CheckConstraint(
                condition=models.Q(("app__in", ["documents", "expenses"])), name="ref_valid_app"
            ),
        ),
        migrations.AddConstraint(
            model_name="grant",
            constraint=models.UniqueConstraint(
                fields=("resource", "user", "kind"), name="ref_unique_grant"
            ),
        ),
        migrations.AddConstraint(
            model_name="grant",
            constraint=models.CheckConstraint(
                condition=models.Q(("kind__in", ["group", "direct"])), name="ref_valid_grant"
            ),
        ),
        migrations.AddConstraint(
            model_name="boundedfault",
            constraint=models.UniqueConstraint(
                fields=("resource", "user"), name="ref_unique_fault"
            ),
        ),
        migrations.AddConstraint(
            model_name="boundedfault",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("expires_at__gt", models.F("started_at")),
                    (
                        "expires_at__lte",
                        django.db.models.expressions.CombinedExpression(
                            models.F("started_at"),
                            "+",
                            models.Value(datetime.timedelta(seconds=600)),
                        ),
                    ),
                ),
                name="ref_bounded_fault",
            ),
        ),
    ]
