# Generated by Django 5.2.17 on 2026-10-01 22:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reference_lab", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="outbox",
            name="lease_token",
            field=models.UUIDField(null=True),
        ),
        migrations.AddField(
            model_name="outbox",
            name="leased_until",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddConstraint(
            model_name="outbox",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("lease_token__isnull", True), ("leased_until__isnull", True)),
                    models.Q(("lease_token__isnull", False), ("leased_until__isnull", False)),
                    _connector="OR",
                ),
                name="ref_outbox_lease_pair",
            ),
        ),
    ]
