# Generated by Django 5.2.17 on 2026-10-02 12:55

import datetime

import django.db.models.deletion
import django.db.models.expressions
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reference_lab", "0002_outbox_lease_token_outbox_leased_until_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BoundedHeaderFault",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("enabled", models.BooleanField(default=False)),
                ("started_at", models.DateTimeField()),
                ("expires_at", models.DateTimeField()),
                (
                    "resource",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="reference_lab.resource"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("resource", "user"), name="ref_unique_header_fault"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("expires_at__gt", models.F("started_at")),
                            (
                                "expires_at__lte",
                                django.db.models.expressions.CombinedExpression(
                                    models.F("started_at"),
                                    "+",
                                    models.Value(datetime.timedelta(seconds=600)),
                                ),
                            ),
                        ),
                        name="ref_bounded_header_fault",
                    ),
                ],
            },
        ),
    ]
